add move
alex-melnyk/flutter_advanced_segment pull request #7
Opened 2021-08-16 12:10 UTC by babaykaVadym

2021-08-16 12:14 UTC, alex-melnyk requested changes

2021-08-16 12:14 UTC, alex-melnyk commented on lib/src/widget.dart
> +      var indexMove = (_itemSize.width * indexKey + touch.localPosition.dx) /
use `final`, those vars never changes.

2021-08-16 12:14 UTC, alex-melnyk commented on lib/src/widget.dart
> +      }
avoid try-catch statement and remove print

2021-08-16 13:06 UTC, alex-melnyk approved these changes

2021-08-16 13:06 UTC, merged

2021-08-18 12:25 UTC, inexuscore commented
@alex-melnyk Much appreciated! I just saw the Github notification, sorry I've been preoccupied with work, busy days. I couldn't find the time to submit a PR. Thank you very much 🍻.